# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Floward-Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Sending the job trigger mail
      run:
        python trigger_email.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install pipfile dependencies
      run: |
        pipenv install -d
    - name: Install playwright
      run: |
        pipenv run playwright install
    - name: Run pytest
      run: |
        pipenv run pytest -v -n 5

    - name: Zipping the report folder
      if: always()
      run:
        python zip_report.py

    - name: Sending the final test report
      if: always()
      run:
        python report_email.py
